name: Set up python
description: Load python with asdf
runs:
  using: composite
  steps:
      # cache the ASDF directory, using values from .tool-versions
      - name: ASDF Cache
        uses: actions/cache@v2
        id: asdf-cache
        with:
          path: ~/.asdf
          key: ${{ runner.os}}-asdf-${{ hashFiles('.tool-versions') }} #runner.os vs CACHE_UUID secret

      # run `asdf install` iff we can't find the cache
      - uses: asdf-vm/actions/install@v1
        if: steps.asdf-cache.outputs.cache-hit != 'true'

      - uses: mbta/actions/reshim-asdf@v1
      
      - name: Install dependencies
        run: |
          pip install build requests splunk-hec-handler awscli black pylint
        shell: bash
      
