name: Deploy Lambda to Prod

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: src

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
  deploy:
    name: Dry-Deploy
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/lambda_deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          environment: prod
