name: Lambda CI

on:
  push:
    branches: main
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

defaults:
  run:
    shell: bash
    working-directory: src

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python_setup
  
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python_setup
      - run: python -m black *.py
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python_setup
      - run: python -m pylint *.py
  
  deploy:
    name: Dry-Deploy
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/lambda_deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dry-run: "true"
          environment: dev
